/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "nanopb/jaiabot/messages/arduino.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jaiabot_protobuf_ArduinoSettings, jaiabot_protobuf_ArduinoSettings, AUTO)


PB_BIND(jaiabot_protobuf_ArduinoActuators, jaiabot_protobuf_ArduinoActuators, AUTO)


PB_BIND(jaiabot_protobuf_ArduinoCommand, jaiabot_protobuf_ArduinoCommand, AUTO)


PB_BIND(jaiabot_protobuf_ArduinoResponse, jaiabot_protobuf_ArduinoResponse, AUTO)


PB_BIND(jaiabot_protobuf_ArduinoDebug, jaiabot_protobuf_ArduinoDebug, AUTO)




