/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "nanopb/jaiabot/messages/feather.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jaiabot_protobuf_LoRaMessage, jaiabot_protobuf_LoRaMessage, 2)


PB_BIND(jaiabot_protobuf_LoRaMessage_ControlSurfaces, jaiabot_protobuf_LoRaMessage_ControlSurfaces, AUTO)





