/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_ATLAS_SCIENTIFIC__OEM_DO_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_ATLAS_SCIENTIFIC__OEM_DO_PB_H_INCLUDED
#include <pb.h>
#include "dccl/option_extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _jaiabot_sensor_protobuf_AtlasScientificOEMDO { 
    /* Measured dissolved oxygen (mg/L) */
    bool has_do_raw;
    double do_raw; 
    /* DO Solubility (mg/L) at current temperature (C), salinity (ppt), and pressure (mmhg) */
    bool has_do_solubility;
    double do_solubility; 
    /* Measured DO / DO Solubility at current temperature (C), salinity (ppt), and pressure (mmhg) */
    bool has_do_saturation_percent;
    double do_saturation_percent; 
    /* DO Solubility at 0 salinity (ppt), same temperature (C) and pressure (mmhg), scaled by observed saturation */
    bool has_do_normalized_solubility;
    double do_normalized_solubility; 
    bool has_temperature;
    double temperature; 
    bool has_temperature_voltage;
    double temperature_voltage; 
} jaiabot_sensor_protobuf_AtlasScientificOEMDO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_do_raw_tag 1
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_do_solubility_tag 2
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_do_saturation_percent_tag 3
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_do_normalized_solubility_tag 4
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_temperature_tag 5
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_temperature_voltage_tag 6

/* Struct field encoding specification for nanopb */
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   do_raw,            1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   do_solubility,     2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   do_saturation_percent,   3) \
X(a, STATIC,   OPTIONAL, DOUBLE,   do_normalized_solubility,   4) \
X(a, STATIC,   OPTIONAL, DOUBLE,   temperature,       5) \
X(a, STATIC,   OPTIONAL, DOUBLE,   temperature_voltage,   6)
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_CALLBACK NULL
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_DEFAULT NULL

extern const pb_msgdesc_t jaiabot_sensor_protobuf_AtlasScientificOEMDO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_fields &jaiabot_sensor_protobuf_AtlasScientificOEMDO_msg

/* Maximum encoded size of messages (where known) */
#define jaiabot_sensor_protobuf_AtlasScientificOEMDO_size 54

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
