/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_ATLAS_SCIENTIFIC__OEM_EC_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_ATLAS_SCIENTIFIC__OEM_EC_PB_H_INCLUDED
#include <pb.h>
#include "dccl/option_extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _jaiabot_sensor_protobuf_AtlasScientificOEMEC { 
    bool has_conductivity;
    double conductivity; /* REQUIRES DCCL 4.2.2 - uncomment when we wrap this in
 [(dccl.field) = {
 units {
         custom {
             unit: "jaiabot::units::microsiemens_per_cm_unit"
             header: "jaiabot/units/conductivity.h"
         }
     }
 }]; */
    bool has_total_dissolved_solids;
    double total_dissolved_solids; 
    bool has_salinity;
    double salinity; 
} jaiabot_sensor_protobuf_AtlasScientificOEMEC;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_init_default {false, 0, false, 0, false, 0}
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_init_zero {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_conductivity_tag 1
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_total_dissolved_solids_tag 2
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_salinity_tag 3

/* Struct field encoding specification for nanopb */
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   conductivity,      1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   total_dissolved_solids,   2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   salinity,          3)
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_CALLBACK NULL
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_DEFAULT NULL

extern const pb_msgdesc_t jaiabot_sensor_protobuf_AtlasScientificOEMEC_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_fields &jaiabot_sensor_protobuf_AtlasScientificOEMEC_msg

/* Maximum encoded size of messages (where known) */
#define jaiabot_sensor_protobuf_AtlasScientificOEMEC_size 27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
