/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_CATALOG_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_CATALOG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _jaiabot_sensor_protobuf_Sensor {
    jaiabot_sensor_protobuf_Sensor_NONE = 1,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_EC = 2,
    jaiabot_sensor_protobuf_Sensor_BLUE_ROBOTICS__BAR30 = 3,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_PH = 4,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_DO = 5,
    jaiabot_sensor_protobuf_Sensor_TURNER__C_FLUOR = 6
} jaiabot_sensor_protobuf_Sensor;

/* Helper constants for enums */
#define _jaiabot_sensor_protobuf_Sensor_MIN jaiabot_sensor_protobuf_Sensor_NONE
#define _jaiabot_sensor_protobuf_Sensor_MAX jaiabot_sensor_protobuf_Sensor_TURNER__C_FLUOR
#define _jaiabot_sensor_protobuf_Sensor_ARRAYSIZE ((jaiabot_sensor_protobuf_Sensor)(jaiabot_sensor_protobuf_Sensor_TURNER__C_FLUOR+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
