/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_CATALOG_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_CATALOG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* vendor__product */
typedef enum _jaiabot_sensor_protobuf_Sensor {
    jaiabot_sensor_protobuf_Sensor_NONE = 1,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_EC = 2,
    jaiabot_sensor_protobuf_Sensor_BLUE_ROBOTICS__BAR30 = 3,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_PH = 4,
    jaiabot_sensor_protobuf_Sensor_ATLAS_SCIENTIFIC__OEM_DO = 5,
    jaiabot_sensor_protobuf_Sensor_TURNER__C_FLUOR = 6,
    jaiabot_sensor_protobuf_Sensor_AML__SENSOR = 7
} jaiabot_sensor_protobuf_Sensor;

/* which of several identical sensors on the payload board this is */
typedef enum _jaiabot_sensor_protobuf_SensorInstance {
    jaiabot_sensor_protobuf_SensorInstance_INSTANCE_1 = 1,
    jaiabot_sensor_protobuf_SensorInstance_INSTANCE_2 = 2
} jaiabot_sensor_protobuf_SensorInstance;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _jaiabot_sensor_protobuf_Sensor_MIN jaiabot_sensor_protobuf_Sensor_NONE
#define _jaiabot_sensor_protobuf_Sensor_MAX jaiabot_sensor_protobuf_Sensor_AML__SENSOR
#define _jaiabot_sensor_protobuf_Sensor_ARRAYSIZE ((jaiabot_sensor_protobuf_Sensor)(jaiabot_sensor_protobuf_Sensor_AML__SENSOR+1))

#define _jaiabot_sensor_protobuf_SensorInstance_MIN jaiabot_sensor_protobuf_SensorInstance_INSTANCE_1
#define _jaiabot_sensor_protobuf_SensorInstance_MAX jaiabot_sensor_protobuf_SensorInstance_INSTANCE_2
#define _jaiabot_sensor_protobuf_SensorInstance_ARRAYSIZE ((jaiabot_sensor_protobuf_SensorInstance)(jaiabot_sensor_protobuf_SensorInstance_INSTANCE_2+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
