/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_METADATA_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_METADATA_PB_H_INCLUDED
#include <pb.h>
#include "dccl/option_extensions.pb.h"
#include "jaiabot/messages/sensor/catalog.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _jaiabot_sensor_protobuf_Metadata_Calibration { 
    bool has_time_performed;
    uint64_t time_performed; 
    bool has_time_to_recalibrate;
    uint64_t time_to_recalibrate; 
    bool has_confirmation;
    int32_t confirmation; 
} jaiabot_sensor_protobuf_Metadata_Calibration;

typedef struct _jaiabot_sensor_protobuf_Metadata_MetadataValue { 
    char key[16]; 
    char value[64]; 
} jaiabot_sensor_protobuf_Metadata_MetadataValue;

typedef struct _jaiabot_sensor_protobuf_Metadata { 
    jaiabot_sensor_protobuf_Sensor sensor; 
    bool has_sensor_version;
    int32_t sensor_version; 
    bool has_calibration;
    jaiabot_sensor_protobuf_Metadata_Calibration calibration; 
    bool has_time_purchased;
    uint64_t time_purchased; 
    pb_size_t metadata_count;
    jaiabot_sensor_protobuf_Metadata_MetadataValue metadata[16]; 
    bool has_payload_board_version;
    int32_t payload_board_version; 
    bool has_init_failed;
    bool init_failed; 
} jaiabot_sensor_protobuf_Metadata;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jaiabot_sensor_protobuf_Metadata_init_default {_jaiabot_sensor_protobuf_Sensor_MIN, false, 0, false, jaiabot_sensor_protobuf_Metadata_Calibration_init_default, false, 0, 0, {jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default}, false, 0, false, 0}
#define jaiabot_sensor_protobuf_Metadata_Calibration_init_default {false, 0, false, 0, false, 0}
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_init_default {"", ""}
#define jaiabot_sensor_protobuf_Metadata_init_zero {_jaiabot_sensor_protobuf_Sensor_MIN, false, 0, false, jaiabot_sensor_protobuf_Metadata_Calibration_init_zero, false, 0, 0, {jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero, jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero}, false, 0, false, 0}
#define jaiabot_sensor_protobuf_Metadata_Calibration_init_zero {false, 0, false, 0, false, 0}
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_init_zero {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_sensor_protobuf_Metadata_Calibration_time_performed_tag 1
#define jaiabot_sensor_protobuf_Metadata_Calibration_time_to_recalibrate_tag 2
#define jaiabot_sensor_protobuf_Metadata_Calibration_confirmation_tag 3
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_key_tag 1
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_value_tag 2
#define jaiabot_sensor_protobuf_Metadata_sensor_tag 1
#define jaiabot_sensor_protobuf_Metadata_sensor_version_tag 2
#define jaiabot_sensor_protobuf_Metadata_calibration_tag 3
#define jaiabot_sensor_protobuf_Metadata_time_purchased_tag 4
#define jaiabot_sensor_protobuf_Metadata_metadata_tag 5
#define jaiabot_sensor_protobuf_Metadata_payload_board_version_tag 6
#define jaiabot_sensor_protobuf_Metadata_init_failed_tag 7

/* Struct field encoding specification for nanopb */
#define jaiabot_sensor_protobuf_Metadata_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    sensor,            1) \
X(a, STATIC,   OPTIONAL, INT32,    sensor_version,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  calibration,       3) \
X(a, STATIC,   OPTIONAL, UINT64,   time_purchased,    4) \
X(a, STATIC,   REPEATED, MESSAGE,  metadata,          5) \
X(a, STATIC,   OPTIONAL, INT32,    payload_board_version,   6) \
X(a, STATIC,   OPTIONAL, BOOL,     init_failed,       7)
#define jaiabot_sensor_protobuf_Metadata_CALLBACK NULL
#define jaiabot_sensor_protobuf_Metadata_DEFAULT (const pb_byte_t*)"\x08\x01\x00"
#define jaiabot_sensor_protobuf_Metadata_calibration_MSGTYPE jaiabot_sensor_protobuf_Metadata_Calibration
#define jaiabot_sensor_protobuf_Metadata_metadata_MSGTYPE jaiabot_sensor_protobuf_Metadata_MetadataValue

#define jaiabot_sensor_protobuf_Metadata_Calibration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   time_performed,    1) \
X(a, STATIC,   OPTIONAL, UINT64,   time_to_recalibrate,   2) \
X(a, STATIC,   OPTIONAL, INT32,    confirmation,      3)
#define jaiabot_sensor_protobuf_Metadata_Calibration_CALLBACK NULL
#define jaiabot_sensor_protobuf_Metadata_Calibration_DEFAULT NULL

#define jaiabot_sensor_protobuf_Metadata_MetadataValue_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   key,               1) \
X(a, STATIC,   REQUIRED, STRING,   value,             2)
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_CALLBACK NULL
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_DEFAULT NULL

extern const pb_msgdesc_t jaiabot_sensor_protobuf_Metadata_msg;
extern const pb_msgdesc_t jaiabot_sensor_protobuf_Metadata_Calibration_msg;
extern const pb_msgdesc_t jaiabot_sensor_protobuf_Metadata_MetadataValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_sensor_protobuf_Metadata_fields &jaiabot_sensor_protobuf_Metadata_msg
#define jaiabot_sensor_protobuf_Metadata_Calibration_fields &jaiabot_sensor_protobuf_Metadata_Calibration_msg
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_fields &jaiabot_sensor_protobuf_Metadata_MetadataValue_msg

/* Maximum encoded size of messages (where known) */
#define jaiabot_sensor_protobuf_Metadata_Calibration_size 33
#define jaiabot_sensor_protobuf_Metadata_MetadataValue_size 82
#define jaiabot_sensor_protobuf_Metadata_size    1416

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
