/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "nanopb/jaiabot/messages/sensor/metadata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jaiabot_sensor_protobuf_Metadata, jaiabot_sensor_protobuf_Metadata, 2)


PB_BIND(jaiabot_sensor_protobuf_Metadata_Calibration, jaiabot_sensor_protobuf_Metadata_Calibration, AUTO)


PB_BIND(jaiabot_sensor_protobuf_Metadata_MetadataValue, jaiabot_sensor_protobuf_Metadata_MetadataValue, AUTO)



