/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_JAIABOT_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_SALINITY_PB_H_INCLUDED
#define PB_JAIABOT_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_SALINITY_PB_H_INCLUDED
#include <pb.h>
#include "dccl/option_extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _jaiabot_protobuf_SalinityData {
    double conductivity;
    double total_dissolved_solids;
    double salinity;
    double specific_gravity;
} jaiabot_protobuf_SalinityData;


/* Initializer values for message structs */
#define jaiabot_protobuf_SalinityData_init_default {0, 0, 0, 0}
#define jaiabot_protobuf_SalinityData_init_zero  {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_protobuf_SalinityData_conductivity_tag 1
#define jaiabot_protobuf_SalinityData_total_dissolved_solids_tag 2
#define jaiabot_protobuf_SalinityData_salinity_tag 3
#define jaiabot_protobuf_SalinityData_specific_gravity_tag 4

/* Struct field encoding specification for nanopb */
#define jaiabot_protobuf_SalinityData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   conductivity,      1) \
X(a, STATIC,   REQUIRED, DOUBLE,   total_dissolved_solids,   2) \
X(a, STATIC,   REQUIRED, DOUBLE,   salinity,          3) \
X(a, STATIC,   REQUIRED, DOUBLE,   specific_gravity,   4)
#define jaiabot_protobuf_SalinityData_CALLBACK NULL
#define jaiabot_protobuf_SalinityData_DEFAULT NULL

extern const pb_msgdesc_t jaiabot_protobuf_SalinityData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_protobuf_SalinityData_fields &jaiabot_protobuf_SalinityData_msg

/* Maximum encoded size of messages (where known) */
#define jaiabot_protobuf_SalinityData_size       36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
