/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "nanopb/jaiabot/messages/sensor/sensor_core.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jaiabot_sensor_protobuf_SensorRequest, jaiabot_sensor_protobuf_SensorRequest, 2)


PB_BIND(jaiabot_sensor_protobuf_SensorData, jaiabot_sensor_protobuf_SensorData, 2)


PB_BIND(jaiabot_sensor_protobuf_SensorThreadConfig, jaiabot_sensor_protobuf_SensorThreadConfig, 2)




