/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_TURNER__C_FLUOR_PB_H_INCLUDED
#define PB_JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_TURNER__C_FLUOR_PB_H_INCLUDED
#include <pb.h>
#include "dccl/option_extensions.pb.h"
#include "jaiabot/messages/sensor/catalog.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _jaiabot_sensor_protobuf_TurnerCFluor {
    /* notional - add units and additional fields as needed */
    bool has_concentration;
    double concentration;
    bool has_concentration_voltage;
    double concentration_voltage;
    bool has_instance;
    jaiabot_sensor_protobuf_SensorInstance instance;
    /* set by the driver from this instance's coefficients, never by the MCU */
    bool has_analyte_name;
    char analyte_name[32];
} jaiabot_sensor_protobuf_TurnerCFluor;

typedef struct _jaiabot_sensor_protobuf_FluorCoefficients {
    bool has_offset;
    double offset;
    bool has_coefficient;
    double coefficient;
    bool has_serial_number;
    int32_t serial_number;
    /* what this probe measures, e.g. "Chlorophyll-a" */
    pb_callback_t analyte_name;
} jaiabot_sensor_protobuf_FluorCoefficients;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jaiabot_sensor_protobuf_TurnerCFluor_init_default {false, 0, false, 0, false, jaiabot_sensor_protobuf_SensorInstance_INSTANCE_1, false, ""}
#define jaiabot_sensor_protobuf_FluorCoefficients_init_default {false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define jaiabot_sensor_protobuf_TurnerCFluor_init_zero {false, 0, false, 0, false, _jaiabot_sensor_protobuf_SensorInstance_MIN, false, ""}
#define jaiabot_sensor_protobuf_FluorCoefficients_init_zero {false, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_sensor_protobuf_TurnerCFluor_concentration_tag 1
#define jaiabot_sensor_protobuf_TurnerCFluor_concentration_voltage_tag 2
#define jaiabot_sensor_protobuf_TurnerCFluor_instance_tag 3
#define jaiabot_sensor_protobuf_TurnerCFluor_analyte_name_tag 4
#define jaiabot_sensor_protobuf_FluorCoefficients_offset_tag 1
#define jaiabot_sensor_protobuf_FluorCoefficients_coefficient_tag 2
#define jaiabot_sensor_protobuf_FluorCoefficients_serial_number_tag 3
#define jaiabot_sensor_protobuf_FluorCoefficients_analyte_name_tag 4

/* Struct field encoding specification for nanopb */
#define jaiabot_sensor_protobuf_TurnerCFluor_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   concentration,     1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   concentration_voltage,   2) \
X(a, STATIC,   OPTIONAL, UENUM,    instance,          3) \
X(a, STATIC,   OPTIONAL, STRING,   analyte_name,      4)
#define jaiabot_sensor_protobuf_TurnerCFluor_CALLBACK NULL
#define jaiabot_sensor_protobuf_TurnerCFluor_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

#define jaiabot_sensor_protobuf_FluorCoefficients_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   offset,            1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   coefficient,       2) \
X(a, STATIC,   OPTIONAL, INT32,    serial_number,     3) \
X(a, CALLBACK, OPTIONAL, STRING,   analyte_name,      4)
#define jaiabot_sensor_protobuf_FluorCoefficients_CALLBACK pb_default_field_callback
#define jaiabot_sensor_protobuf_FluorCoefficients_DEFAULT NULL

extern const pb_msgdesc_t jaiabot_sensor_protobuf_TurnerCFluor_msg;
extern const pb_msgdesc_t jaiabot_sensor_protobuf_FluorCoefficients_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_sensor_protobuf_TurnerCFluor_fields &jaiabot_sensor_protobuf_TurnerCFluor_msg
#define jaiabot_sensor_protobuf_FluorCoefficients_fields &jaiabot_sensor_protobuf_FluorCoefficients_msg

/* Maximum encoded size of messages (where known) */
/* jaiabot_sensor_protobuf_FluorCoefficients_size depends on runtime parameters */
#define JAIABOT_SENSOR_PROTOBUF_NANOPB_JAIABOT_MESSAGES_SENSOR_TURNER__C_FLUOR_PB_H_MAX_SIZE jaiabot_sensor_protobuf_TurnerCFluor_size
#define jaiabot_sensor_protobuf_TurnerCFluor_size 53

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
