/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ATLAS_SCIENTIFIC__OEM_DO_PB_H_INCLUDED
#define PB_ATLAS_SCIENTIFIC__OEM_DO_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AtlasScientificOEMDO {
    bool has_dissolved_oxygen;
    double dissolved_oxygen;
} AtlasScientificOEMDO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AtlasScientificOEMDO_init_default        {false, 0}
#define AtlasScientificOEMDO_init_zero           {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AtlasScientificOEMDO_dissolved_oxygen_tag 1

/* Struct field encoding specification for nanopb */
#define AtlasScientificOEMDO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   dissolved_oxygen,   1)
#define AtlasScientificOEMDO_CALLBACK NULL
#define AtlasScientificOEMDO_DEFAULT NULL

extern const pb_msgdesc_t AtlasScientificOEMDO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AtlasScientificOEMDO_fields &AtlasScientificOEMDO_msg

/* Maximum encoded size of messages (where known) */
#define ATLAS_SCIENTIFIC__OEM_DO_PB_H_MAX_SIZE   AtlasScientificOEMDO_size
#define AtlasScientificOEMDO_size                9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
