/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ATLAS_SCIENTIFIC__OEM_EC_PB_H_INCLUDED
#define PB_ATLAS_SCIENTIFIC__OEM_EC_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AtlasScientificOEMEC {
    bool has_conductivity;
    double conductivity;
    bool has_total_dissolved_solids;
    double total_dissolved_solids;
    bool has_salinity;
    double salinity;
    bool has_specific_gravity;
    double specific_gravity;
} AtlasScientificOEMEC;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AtlasScientificOEMEC_init_default        {false, 0, false, 0, false, 0, false, 0}
#define AtlasScientificOEMEC_init_zero           {false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AtlasScientificOEMEC_conductivity_tag    1
#define AtlasScientificOEMEC_total_dissolved_solids_tag 2
#define AtlasScientificOEMEC_salinity_tag        3
#define AtlasScientificOEMEC_specific_gravity_tag 4

/* Struct field encoding specification for nanopb */
#define AtlasScientificOEMEC_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   conductivity,      1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   total_dissolved_solids,   2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   salinity,          3) \
X(a, STATIC,   OPTIONAL, DOUBLE,   specific_gravity,   4)
#define AtlasScientificOEMEC_CALLBACK NULL
#define AtlasScientificOEMEC_DEFAULT NULL

extern const pb_msgdesc_t AtlasScientificOEMEC_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AtlasScientificOEMEC_fields &AtlasScientificOEMEC_msg

/* Maximum encoded size of messages (where known) */
#define ATLAS_SCIENTIFIC__OEM_EC_PB_H_MAX_SIZE   AtlasScientificOEMEC_size
#define AtlasScientificOEMEC_size                36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
