/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "nanopb/dccl/option_extensions.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dccl_DCCLFieldOptions, dccl_DCCLFieldOptions, 2)


PB_BIND(dccl_DCCLFieldOptions_Units, dccl_DCCLFieldOptions_Units, AUTO)


PB_BIND(dccl_DCCLFieldOptions_Conditions, dccl_DCCLFieldOptions_Conditions, AUTO)


PB_BIND(dccl_DCCLMessageOptions, dccl_DCCLMessageOptions, AUTO)


/* Definition for extension field dccl_field */
typedef struct _dccl_field_extmsg {
    dccl_DCCLFieldOptions field;
} dccl_field_extmsg;
#define dccl_field_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  field,           1012)
#define dccl_field_extmsg_CALLBACK NULL
#define dccl_field_extmsg_DEFAULT NULL
#define dccl_field_extmsg_field_MSGTYPE dccl_DCCLFieldOptions
pb_byte_t dccl_field_extmsg_default[] = {0x00};
PB_BIND(dccl_field_extmsg, dccl_field_extmsg, 2)
const pb_extension_type_t dccl_field = {
    NULL,
    NULL,
    &dccl_field_extmsg_msg
};

/* Definition for extension field dccl_msg */
typedef struct _dccl_msg_extmsg {
    dccl_DCCLMessageOptions msg;
} dccl_msg_extmsg;
#define dccl_msg_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  msg,             1012)
#define dccl_msg_extmsg_CALLBACK NULL
#define dccl_msg_extmsg_DEFAULT NULL
#define dccl_msg_extmsg_msg_MSGTYPE dccl_DCCLMessageOptions
pb_byte_t dccl_msg_extmsg_default[] = {0x00};
PB_BIND(dccl_msg_extmsg, dccl_msg_extmsg, 2)
const pb_extension_type_t dccl_msg = {
    NULL,
    NULL,
    &dccl_msg_extmsg_msg
};


#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

